Add Styling
moise-mulungu/bookstore-app pull request #5
Opened 2022-04-15 15:29 UTC by moise-mulungu

On this milestone, I:
- Used the Zeplin credentials for the project
- Styled the navbar, and the book
- Used the information detailed in Zeplin 
- Updated the README file
- Fixed linter errors

2022-04-15 16:35 UTC, micheaol requested changes
Hi @moise-mulungu , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-15 16:35 UTC, micheaol commented on src/components/Navigation.js
> +        <img src="https://img.icons8.com/external-anggara-outline-color-anggara-putra/32/000000/external-avatar-interface-anggara-outline-color-anggara-putra.png" alt="profile" />
Your app is not performing as expected. It keeps refreshing every second. Please see the video attached for the behavior. Kindly fix it.

https://www.loom.com/share/7ac6af2d4150452f9a756f3f04c5995d

2022-04-15 16:35 UTC, micheaol commented on src/components/Book.js
> -        <ul>
Please ensure that the styling is EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/)tyling is EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/).

Your Implementation | Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/163595979-8c017c49-9c42-43e8-a6e2-7e08b1fa9b0e.png) | ![image](https://user-images.githubusercontent.com/10332499/163595942-a25de58f-247e-46d7-9f10-4ef404f41771.png)

Your Implementation | Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/163596117-a763ad19-0c46-4bbd-a9a6-3cd115098de2.png) | ![image](https://user-images.githubusercontent.com/10332499/163596090-f28d4180-c25d-4dee-89e0-856f7886736f.png)


Your Implementation | Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/163596278-038b3df8-4d27-44f7-9a50-712d835f18e1.png) | ![image](https://user-images.githubusercontent.com/10332499/163596253-162826e6-c9fd-4823-bce6-c81f2638216b.png)

2022-04-15 16:35 UTC, micheaol commented on src/App.css
> +  height: 2.313rem;
Please ensure that you use the same `font attributes` as in the original design. To get the fonts or the color, click on the element you want to inspect and you will see the `right pan` like the image below:

![image](https://user-images.githubusercontent.com/10332499/163596665-917f9de4-5003-4e1e-8ed5-73b665b26b7c.png)

2022-04-16 20:43 UTC, DeliceLydia approved these changes
## Hi @moise-mulungu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-16 21:04 UTC, merged